In [1]:
from sklearn.datasets import load_iris  
import numpy as np
from IrisFisher import softmax, softmax_grad, logloss, logloss_grad

In [2]:
data = load_iris()

def UnisonShuffle(a, b):
    ''' Функция совместного перемешивания'''
    assert len(a) == len(b)
    p = np.random.permutation(len(a))
    return a[p], b[p]

In [3]:
X = data["data"]
y_lables = data["target"]
y = np.zeros((len(y_lables), 3))
for i, a in enumerate(y_lables):
    y[i][a] = 1

X, y = UnisonShuffle(X, y)
W = dict()
A = dict()
params = dict()
params["learning rate"] = 0.1
lenX = len(y)
W[0] = 2 * np.random.random((4, 3)) - 1

In [32]:
def forward_prop(X, y, W, A):
    A[0] = np.dot(X, W[0])
    A[1] = softmax(A[0])
    L = logloss(A[1], y)

def back_prop(X, y, W, A, giper_params):
    dLdP = logloss_grad(A[1], y) #1x3
    dPda = softmax_grad(A[1]) # 3x3
    dLda = np.dot(dLdP, dPda).reshape(3, 1) #3x1
    print(dLda.shape)
    print(dLda, X.reshape(1, 4))
    print("--------------------------------------------------------------")
    dLdW = np.dot(dLda, X.reshape(1, 4))
    print(dLdW)
    print(W[0])
    W[0] -= giper_params["learning rate"] * dLdW
    

In [33]:
for i in range(1000):
    forward_prop(X[i%lenX], y[i%lenX], W, A)
    back_prop(X[i%lenX], y[i%lenX], W, A, params)

for i in range(len(y)):
    forward_prop(X[i%lenX], y[i%lenX], W, A)
    print(y[i], A[1])

(3, 1)
[[ 0.42978736]
 [ 0.00718448]
 [-0.43697184]] [[6.4 2.8 5.6 2.2]]
--------------------------------------------------------------
[[ 2.75063909  1.2034046   2.40680921  0.94553219]
 [ 0.04598067  0.02011654  0.04023309  0.01580586]
 [-2.79661976 -1.22352115 -2.44704229 -0.96133804]]
[[ 0.32505199 -0.99981285  0.05235096]
 [-0.69387893  0.93410819  0.54137767]
 [-0.49760059 -0.31555789 -0.49513333]
 [ 0.43595052 -0.1049747  -0.22641742]]


ValueError: operands could not be broadcast together with shapes (4,3) (3,4) (4,3) 